name: one workflow

on:
  workflow_call:



jobs:
  one_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Hello User
        run: echo Hello ${{ inputs.username }}
